In [1]:
import pandas as pd
from sqlalchemy import create_engine
import pymysql

pd.set_option('display.max_columns', None)

# Conexion a la DB

In [2]:
USUARIO = 'root'          
PASSWORD = 'root'  
HOST = 'localhost'         
PORT = '3306'             
DB_NAME = 'semi2'    

cadena_conexion = f"mysql+pymysql://{USUARIO}:{PASSWORD}@{HOST}:{PORT}/{DB_NAME}"

try:
    engine = create_engine(cadena_conexion)
    with engine.connect() as conn:
        print(f"✅ Conexión exitosa a la base de datos MySQL: {DB_NAME}")
except Exception as e:
    print("❌ Error al conectar a MySQL. Verifica tus credenciales.")
    print(f"Detalle: {e}")
    exit()

✅ Conexión exitosa a la base de datos MySQL: semi2

# Carga de datos desde archivos .csv

In [10]:
# Carga de CSVs
try:
    df_compras = pd.read_csv('./archivosCarga/compras.csv', encoding='utf-8')
    df_ventas = pd.read_csv('./archivosCarga/ventas.csv', encoding='utf-8')
    print("Archivos cargados correctamente.")
except FileNotFoundError:
    print("Error: Sube los archivos compras.csv y ventas.csv al mismo directorio del notebook.")

# Muestra las primeras filas para verificar
display(df_compras.head(10))
display(df_ventas.head(10))

Archivos cargados correctamente.

,Fecha,CodProveedor,NombreProveedor,CodProducto,NombreProducto,MarcaProducto,Categoria,CodSucursal,NombreSucursal,Region,Departamento,Unidades,CostoUnitario
0,11/11/2019,P0001,Mercedes Flavio Guerra Pizarro,AC00002,Cerveza Hofbrau Munchen,ZENU,Vinos y Licores,S0004,Sucursal Oeste,Occidente,Huehuetenango,368,285.09
1,08/12/2022,P0001,Mercedes Flavio Guerra Pizarro,AC00003,Queso Camembert,MONTICELLO,Charcutería,S0003,Sucursal Este,Nororiente,Zacapa,235,435.59
2,28/10/2022,P0001,Mercedes Flavio Guerra Pizarro,AC00001,Gaseosa Postobon Uva,POSTOBON,Bebidas,S0001,Sucursal Norte,Metropolitana,Guatemala,282,223.50
3,08/07/2018,P0001,Mercedes Flavio Guerra Pizarro,AC00003,Queso Camembert,MONTICELLO,Charcutería,S0004,Sucursal Oeste,Occidente,Huehuetenango,261,452.27
4,16/08/2020,P0001,Mercedes Flavio Guerra Pizarro,AC00006,Vino espumoso Rothberg,SINFONIA,Vinos y Licores,S0002,Sucursal Sur,Suroccidente,Quetzaltenango,612,82.30
5,13/04/2023,P0001,Mercedes Flavio Guerra Pizarro,AC00003,Queso Camembert,MONTICELLO,Charcutería,S0002,Sucursal Sur,Suroccidente,Quetzaltenango,153,347.35
6,01/03/2023,P0001,Mercedes Flavio Guerra Pizarro,AC00001,Gaseosa Postobon Uva,POSTOBON,Bebidas,S0003,Sucursal Este,Nororiente,Zacapa,540,566.71
7,03/08/Z018,P0001,Mercedes Flavio Guerra Pizarro,AC00006,Vino espumoso Rothberg,SINFONIA,Vinos y Licores,S0001,Sucursal Norte,Metropolitana,Guatemala,794,748.49
8,16/02/2018,P0001,Mercedes Flavio Guerra Pizarro,AC00005,Servilletas Familia Max,ZORBA,Limpieza de cocina,S0002,Sucursal Sur,Suroccidente,Quetzaltenango,470,173.95
9,21/08/2022,P0001,Mercedes Flavio Guerra Pizarro,AC00002,Cerveza Hofbrau Munchen,ZENU,Vinos y Licores,S0001,Sucursal Norte,Metropolitana,Guatemala,302,781.88

,Fecha,CodCliente,NombreCliente,TipoCliente,CodVendedor,NombreVendedor,CodProducto,NombreProducto,MarcaProducto,Categoria,CodSucursal,NombreSucursal,Region,Departamento,Unidades,PrecioUnitario
0,13/07/2021,C0100,Iván Gonzalo Barreto Ordóñez,Mayorista,V0008,Mtro. Hugo Ruelas,AC00004,Vino Gato Blanco,CREM HELADO,Vinos y Licores,S0004,Sucursal Oeste,Occidente,Huehuetenango,294,1104.71
1,21/03/2022,C0100,Iván Gonzalo Barreto Ordóñez,Mayorista,V0007,Eugenio Correa,AC00004,Vino Gato Blanco,CREM HELADO,Vinos y Licores,S0003,Sucursal Este,Nororiente,Zacapa,31,398.48
2,01/11/2020,C0100,Iván Gonzalo Barreto Ordóñez,Mayorista,V0003,Serafín Carvajal,AC00003,Queso Camembert,MONTICELLO,Charcutería,S0002,Sucursal Sur,Suroccidente,Quetzaltenango,277,183.63
3,17/07/2023,C0100,Iván Gonzalo Barreto Ordóñez,Mayorista,V0008,Mtro. Hugo Ruelas,AC00001,Gaseosa Postobon Uva,POSTOBON,Bebidas,S0002,Sucursal Sur,Suroccidente,Quetzaltenango,365,647.15
4,23/12/2018,C0100,Iván Gonzalo Barreto Ordóñez,Mayorista,V0007,Eugenio Correa,AC00006,Vino espumoso Rothberg,SINFONIA,Vinos y Licores,S0003,Sucursal Este,Nororiente,Zacapa,446,944.95
5,30/07/2019,C0100,Iván Gonzalo Barreto Ordóñez,Mayorista,V0005,Emiliano Olivia Villarreal Dueñas,AC00004,Vino Gato Blanco,CREM HELADO,Vinos y Licores,S0002,Sucursal Sur,Suroccidente,Quetzaltenango,428,1282.17
6,16/10/2019,C0099,Isabela Laureano,Mayorista,V0001,Renato de León,AC00005,Servilletas Familia Max,ZORBA,Limpieza de cocina,S0003,Sucursal Este,Nororiente,Zacapa,328,1339.82
7,11/04/2020,C0099,Isabela Laureano,Mayorista,V0002,Leonel Georgina Ornelas Naranjo,AC00001,Gaseosa Postobon Uva,POSTOBON,Bebidas,S0002,Sucursal Sur,Suroccidente,Quetzaltenango,84,591.93
8,Z3/08/2018,C0099,Isabela Laureano,Mayorista,V0007,Eugenio Correa,AC00004,Vino Gato Blanco,CREM HELADO,Vinos y Licores,S0002,Sucursal Sur,Suroccidente,Quetzaltenango,130,322.95
9,09/06/2020,C0099,Isabela Laureano,Mayorista,V0004,Santiago Fabiola Naranjo,AC00003,Queso Camembert,MONTICELLO,Charcutería,S0002,Sucursal Sur,Suroccidente,Quetzaltenango,103,150.71

# Transformación y limpieza

In [11]:
# Función de limpieza para fechas
def limpiar_fecha(fecha_str):
    if pd.isna(fecha_str): return None
    # Corrige errores comunes de OCR (Z por 2, O por 0)
    fecha_str = str(fecha_str).replace('Z', '2').replace('O', '0')
    return fecha_str

# Limpieza de Fechas 
df_compras['Fecha'] = pd.to_datetime(df_compras['Fecha'].apply(limpiar_fecha), dayfirst=True, errors='coerce')
df_ventas['Fecha'] = pd.to_datetime(df_ventas['Fecha'].apply(limpiar_fecha), dayfirst=True, errors='coerce')

# Eliminar filas que no tengan fecha válida
df_compras.dropna(subset=['Fecha'], inplace=True)
df_ventas.dropna(subset=['Fecha'], inplace=True)

# Limpieza de Valores Negativos
df_ventas['PrecioUnitario'] = df_ventas['PrecioUnitario'].abs()
df_ventas['Unidades'] = df_ventas['Unidades'].abs()

df_compras['CostoUnitario'] = df_compras['CostoUnitario'].abs()
df_compras['Unidades'] = df_compras['Unidades'].abs()

print("Transformación y limpieza completada.")

display(df_compras.head(3))
display(df_ventas.head(3))

Transformación y limpieza completada.

,Fecha,CodProveedor,NombreProveedor,CodProducto,NombreProducto,MarcaProducto,Categoria,CodSucursal,NombreSucursal,Region,Departamento,Unidades,CostoUnitario
0,2019-11-11,P0001,Mercedes Flavio Guerra Pizarro,AC00002,Cerveza Hofbrau Munchen,ZENU,Vinos y Licores,S0004,Sucursal Oeste,Occidente,Huehuetenango,368,285.09
1,2022-12-08,P0001,Mercedes Flavio Guerra Pizarro,AC00003,Queso Camembert,MONTICELLO,Charcutería,S0003,Sucursal Este,Nororiente,Zacapa,235,435.59
2,2022-10-28,P0001,Mercedes Flavio Guerra Pizarro,AC00001,Gaseosa Postobon Uva,POSTOBON,Bebidas,S0001,Sucursal Norte,Metropolitana,Guatemala,282,223.50

,Fecha,CodCliente,NombreCliente,TipoCliente,CodVendedor,NombreVendedor,CodProducto,NombreProducto,MarcaProducto,Categoria,CodSucursal,NombreSucursal,Region,Departamento,Unidades,PrecioUnitario
0,2021-07-13,C0100,Iván Gonzalo Barreto Ordóñez,Mayorista,V0008,Mtro. Hugo Ruelas,AC00004,Vino Gato Blanco,CREM HELADO,Vinos y Licores,S0004,Sucursal Oeste,Occidente,Huehuetenango,294,1104.71
1,2022-03-21,C0100,Iván Gonzalo Barreto Ordóñez,Mayorista,V0007,Eugenio Correa,AC00004,Vino Gato Blanco,CREM HELADO,Vinos y Licores,S0003,Sucursal Este,Nororiente,Zacapa,31,398.48
2,2020-11-01,C0100,Iván Gonzalo Barreto Ordóñez,Mayorista,V0003,Serafín Carvajal,AC00003,Queso Camembert,MONTICELLO,Charcutería,S0002,Sucursal Sur,Suroccidente,Quetzaltenango,277,183.63

# Creacion de dimensiones y hechos

In [12]:
# Dimensión Fecha
fechas_unicas = pd.concat([df_compras['Fecha'], df_ventas['Fecha']]).unique()
dim_fecha = pd.DataFrame({'Fecha': fechas_unicas})
dim_fecha['id_fecha'] = dim_fecha['Fecha'].dt.strftime('%Y%m%d').astype(int)
dim_fecha['anio'] = dim_fecha['Fecha'].dt.year
dim_fecha['mes'] = dim_fecha['Fecha'].dt.month
nombres_meses = {1:'Enero', 2:'Febrero', 3:'Marzo', 4:'Abril', 5:'Mayo', 6:'Junio', 
                 7:'Julio', 8:'Agosto', 9:'Septiembre', 10:'Octubre', 11:'Noviembre', 12:'Diciembre'}
dim_fecha['nombre_mes'] = dim_fecha['mes'].map(nombres_meses)
dim_fecha['dia'] = dim_fecha['Fecha'].dt.day
dim_fecha['trimestre'] = dim_fecha['Fecha'].dt.quarter.apply(lambda x: f"Q{x}")

dim_fecha_final = dim_fecha[['id_fecha', 'anio', 'nombre_mes', 'trimestre', 'dia', 'mes']].copy()

# Dimensión Producto (Unificando compras y ventas)
cols_prod = ['CodProducto', 'NombreProducto', 'MarcaProducto', 'Categoria']
dim_producto = pd.concat([df_compras[cols_prod], df_ventas[cols_prod]]).drop_duplicates(subset=['CodProducto']).reset_index(drop=True)

# Dimensión Sucursal
cols_suc = ['CodSucursal', 'NombreSucursal', 'Region', 'Departamento']
dim_sucursal = pd.concat([df_compras[cols_suc], df_ventas[cols_suc]]).drop_duplicates(subset=['CodSucursal']).reset_index(drop=True)

# Otras dimensiones
dim_cliente = df_ventas[['CodCliente', 'NombreCliente', 'TipoCliente']].drop_duplicates(subset=['CodCliente']).dropna(subset=['CodCliente'])
dim_vendedor = df_ventas[['CodVendedor', 'NombreVendedor']].drop_duplicates(subset=['CodVendedor']).dropna(subset=['CodVendedor'])
dim_proveedor = df_compras[['CodProveedor', 'NombreProveedor']].drop_duplicates(subset=['CodProveedor']).dropna(subset=['CodProveedor'])


print("Dimensiones creadas.")
display(dim_producto.head(3))

mapa_fechas = dim_fecha.set_index('Fecha')['id_fecha'].to_dict()


# -- Fac Compras --
fac_compras = df_compras.copy()
fac_compras['id_fecha'] = fac_compras['Fecha'].map(mapa_fechas)
fac_compras['total_compra'] = fac_compras['Unidades'] * fac_compras['CostoUnitario']
fac_compras = fac_compras[['id_fecha', 'CodProducto', 'CodSucursal', 'CodProveedor', 'Unidades', 'CostoUnitario', 'total_compra']]

# -- Fac Ventas --
fac_ventas = df_ventas.copy()
fac_ventas['id_fecha'] = fac_ventas['Fecha'].map(mapa_fechas)
fac_ventas['total_venta'] = fac_ventas['Unidades'] * fac_ventas['PrecioUnitario']
fac_ventas = fac_ventas[['id_fecha', 'CodProducto', 'CodSucursal', 'CodCliente', 'CodVendedor', 'Unidades', 'PrecioUnitario', 'total_venta']]

fac_compras.dropna(subset=['CodProveedor', 'CodProducto', 'CodSucursal'], inplace=True)
fac_ventas.dropna(subset=['CodCliente', 'CodVendedor', 'CodProducto', 'CodSucursal'], inplace=True)

print("Tablas de hechos creadas.")
display(fac_ventas.head(3))

Dimensiones creadas.

  CodProducto           NombreProducto MarcaProducto        Categoria
0     AC00002  Cerveza Hofbrau Munchen          ZENU  Vinos y Licores
1     AC00003          Queso Camembert    MONTICELLO      Charcutería
2     AC00001     Gaseosa Postobon Uva      POSTOBON          Bebidas

Tablas de hechos creadas.

,id_fecha,CodProducto,CodSucursal,CodCliente,CodVendedor,Unidades,PrecioUnitario,total_venta
0,20210713,AC00004,S0004,C0100,V0008,294,1104.71,324784.74
1,20220321,AC00004,S0003,C0100,V0007,31,398.48,12352.88
2,20201101,AC00003,S0002,C0100,V0003,277,183.63,50865.51

# Cargar datos a la BD

In [14]:
print("\n--- 3. Iniciando Carga a MySQL ---")

tablas_etl = {
    'dim_fecha': dim_fecha_final,
    'dim_producto': dim_producto,
    'dim_sucursal': dim_sucursal,
    'dim_cliente': dim_cliente,
    'dim_vendedor': dim_vendedor,
    'dim_proveedor': dim_proveedor,
    'fac_ventas': fac_ventas,
    'fac_compras': fac_compras
}

for nombre, df in tablas_etl.items():
    try:
        # Usamos 'append' para insertar en las tablas ya creadas con SQL
        # index=False es vital para no intentar subir el índice de Pandas
        df.to_sql(name=nombre, con=engine, if_exists='append', index=False)
        print(f"   -> Tabla '{nombre}' cargada ({len(df)} registros).")
    except Exception as e:
        # Si da error de duplicados (IntegrityError), es porque ya corriste el script antes.
        # Puedes ignorarlo o borrar los datos manualmente en MySQL antes de correrlo.
        print(f"   ⚠️ Error cargando '{nombre}': {e}")
        # Sugerencia visual para el usuario
        if "Duplicate entry" in str(e):
            print("      (Los datos ya existían, no se duplicaron).")

print("✅ Carga finalizada.")

--- 3. Iniciando Carga a MySQL ---
   -> Tabla 'dim_fecha' cargada (1381 registros).
   -> Tabla 'dim_producto' cargada (6 registros).
   -> Tabla 'dim_sucursal' cargada (4 registros).
   -> Tabla 'dim_cliente' cargada (109 registros).
   -> Tabla 'dim_vendedor' cargada (10 registros).
   -> Tabla 'dim_proveedor' cargada (100 registros).
   -> Tabla 'fac_ventas' cargada (1000 registros).
   -> Tabla 'fac_compras' cargada (995 registros).
✅ Carga finalizada.

# Consultas realizadas

### Consulta 1

In [16]:
# Consulta 1: Total de compras y ventas por año

query1 = """
SELECT 
    f.anio,
    SUM(v.total_venta) as Total_Ventas,
    SUM(c.total_compra) as Total_Compras
FROM dim_fecha f
LEFT JOIN fac_ventas v ON f.id_fecha = v.id_fecha
LEFT JOIN fac_compras c ON f.id_fecha = c.id_fecha
GROUP BY f.anio
ORDER BY f.anio;
"""

try:
    res = pd.read_sql(query1, engine)
    if res.empty:
        print("   (Sin resultados)")
    else:
        print(res.to_string(index=False))
except Exception as e:
    print(f"Error SQL: {e}")

 anio  Total_Ventas  Total_Compras
 2018   30465337.82    36763343.66
 2019   30645635.76    33379903.79
 2020   33588327.78    32600986.15
 2021   31992314.74    35435544.86
 2022   26734049.06    27952206.53
 2023   26648602.06    24586058.52
 2024   28139805.96    37281408.35

### Consulta 2

In [21]:
# Consulta 2: Productos con pérdida (Precio Venta < Costo Compra)

query2 = """
SELECT 
    p.NombreProducto,
    AVG(v.PrecioUnitario) as Precio_Promedio_Venta,
    AVG(c.CostoUnitario) as Costo_Promedio_Compra,
    (AVG(v.PrecioUnitario) - AVG(c.CostoUnitario)) as Margen
FROM dim_producto p
JOIN fac_ventas v ON p.CodProducto = v.CodProducto
JOIN fac_compras c ON p.CodProducto = c.CodProducto
GROUP BY p.NombreProducto
HAVING AVG(v.PrecioUnitario) < AVG(c.CostoUnitario)
ORDER BY Margen ASC;
"""

try:
    res = pd.read_sql(query2, engine)
    if res.empty:
        print("   (Sin resultados)")
    else:
        print(res.to_string(index=False))
except Exception as e:
    print(f"Error SQL: {e}")

   (Sin resultados)

### Consulta 3

In [20]:
# Consulta 3: Top 5 productos más vendidos por unidades

query3 = """
SELECT 
    p.NombreProducto,
    SUM(v.Unidades) as Total_Unidades_Vendidas
FROM fac_ventas v
JOIN dim_producto p ON v.CodProducto = p.CodProducto
GROUP BY p.NombreProducto
ORDER BY Total_Unidades_Vendidas DESC
LIMIT 5;
"""

try:
    res = pd.read_sql(query3, engine)
    if res.empty:
        print("   (Sin resultados)")
    else:
        print(res.to_string(index=False))
except Exception as e:
    print(f"Error SQL: {e}")

         NombreProducto  Total_Unidades_Vendidas
       Vino Gato Blanco                  44636.0
        Queso Camembert                  43509.0
   Gaseosa Postobon Uva                  42552.0
 Vino espumoso Rothberg                  42103.0
Servilletas Familia Max                  41910.0

### Consulta 4

In [19]:
# Consulta 4: Ingresos por región y año

query4 = """
SELECT 
    s.Region,
    f.anio,
    SUM(v.total_venta) as Ingresos
FROM fac_ventas v
JOIN dim_sucursal s ON v.CodSucursal = s.CodSucursal
JOIN dim_fecha f ON v.id_fecha = f.id_fecha
GROUP BY s.Region, f.anio
ORDER BY s.Region, f.anio;
"""

try:
    res = pd.read_sql(query4, engine)
    if res.empty:
        print("   (Sin resultados)")
    else:
        print(res.to_string(index=False))
except Exception as e:
    print(f"Error SQL: {e}")

       Region  anio   Ingresos
Metropolitana  2018 7972538.20
Metropolitana  2019 6542926.76
Metropolitana  2020 7729577.02
Metropolitana  2021 7055574.17
Metropolitana  2022 5662042.86
Metropolitana  2023 9487888.94
Metropolitana  2024 5643810.08
   Nororiente  2018 6270833.01
   Nororiente  2019 7881949.08
   Nororiente  2020 7837877.10
   Nororiente  2021 8318346.04
   Nororiente  2022 4843288.07
   Nororiente  2023 7107915.32
   Nororiente  2024 7061537.80
    Occidente  2018 8083283.11
    Occidente  2019 8437261.88
    Occidente  2020 7394524.87
    Occidente  2021 6695197.74
    Occidente  2022 6377111.19
    Occidente  2023 6145450.35
    Occidente  2024 7260685.47
 Suroccidente  2018 4621155.32
 Suroccidente  2019 6037323.03
 Suroccidente  2020 8423058.80
 Suroccidente  2021 7454687.88
 Suroccidente  2022 7518453.50
 Suroccidente  2023 3612386.47
 Suroccidente  2024 5940290.84

### Consulta 5

In [18]:
# Consulta: Proveedores con mayor volumen de compras

query5 = """
SELECT 
    p.NombreProveedor,
    SUM(c.Unidades) as Total_Unidades_Compradas,
    SUM(c.total_compra) as Costo_Total_Inversion
FROM fac_compras c
JOIN dim_proveedor p ON c.CodProveedor = p.CodProveedor
GROUP BY p.NombreProveedor
ORDER BY Total_Unidades_Compradas DESC
LIMIT 5;
"""

try:
    res = pd.read_sql(query5, engine)
    if res.empty:
        print("   (Sin resultados)")
    else:
        print(res.to_string(index=False))
except Exception as e:
    print(f"Error SQL: {e}")

       NombreProveedor  Total_Unidades_Compradas  Costo_Total_Inversion
   Jos Carlota Sanches                    8320.0             4351531.79
           Estela Niño                    7979.0             3841924.76
   Lourdes Covarrubias                    7769.0             3868323.93
 Alvaro Vergara Arenas                    7708.0             3263051.04
Gustavo Perla Zaragoza                    7038.0             4036840.87